import { useState } from "react";

import ScoreHeader from "../components/UI/Scorecard/ScoreHeader";
import ScoreProfileCard from "../components/UI/Scorecard/ScoreProfileCard";
import JourneyProgress from "../components/UI/Scorecard/JourneyProgress";
import ScoreStats from "../components/UI/Scorecard/ScoreStats";
import RouteActivity from "../components/UI/Scorecard/RouteActivity";
import CrowdReporterCard from "../components/UI/Scorecard/CrowdReporterCard";
import Achievements from "../components/UI/Scorecard/Achievements";
import VisitHistory from "../components/UI/Scorecard/VisitHistory";


import { getScorecardRouteSummary } from "../utils/scorecardRouteMetrics";

const ScorecardPage = ({
  scorecard = null,
  user = null,
  pandals = [],
  userLocation,
  routeData = null,
  routeSegments = [],
  selectedPandals = [],
  activeRouteMode = null,
  onBack,
}) => {
  

  /*
   * SCORECARD SOURCE OF TRUTH
   *
   * Visits and points come from the scorecard state maintained
   * by App.jsx.
   */
  const visits = Array.isArray(scorecard?.visits)
    ? scorecard.visits
    : [];

  const totalPoints = Number(scorecard?.totalPoints) || 0;

  /*
   * TOTAL PANDALS
   *
   * This comes from the actual pandal data loaded by the app.
   */
  const totalPandals = Array.isArray(pandals)
    ? pandals.length
    : 0;

  /*
   * VISITED COUNT
   *
   * A pandal is considered visited only when an actual check-in
   * has been added to the scorecard.
   */
  const visitedCount = visits.length;

  /*
   * JOURNEY PROGRESS
   */
  const percentage =
    totalPandals > 0
      ? Math.min(
          Math.round((visitedCount / totalPandals) * 100),
          100
        )
      : 0;

  const remaining = Math.max(
    totalPandals - visitedCount,
    0
  );

  /*
   * CATEGORY COUNTS
   *
   * Derived from real check-in visits.
   */
  const categoryCounts = visits.reduce(
    (counts, visit) => {
      const category = String(
        visit?.category || ""
      ).toLowerCase();

      if (!category) {
        return counts;
      }

      counts[category] =
        (counts[category] || 0) + 1;

      return counts;
    },
    {}
  );

  const categoryCount =
    Object.keys(categoryCounts).length;

  /*
   * ROUTE SUMMARY
   *
   * Derived from the actual route data generated by App.jsx.
   */
  const routeSummary = getScorecardRouteSummary({
    routeData,
    routeSegments,
    selectedPandals,
    activeRouteMode,
  });

  /*
   * STATS PASSED TO CHILD COMPONENTS
   */
  const scorecardStats = {
    visitedCount,
    totalPandals,
    percentage,
    remaining,
    categoryCount,
    totalPoints,
  };

  /*
   * ACHIEVEMENTS ARE DERIVED FROM REAL APP DATA.
   */
  const achievementStats = {
    visited: visitedCount,
    categories: categoryCount,
    progress:
      totalPandals > 0
        ? visitedCount / totalPandals
        : 0,
    hasRoute: Boolean(routeSummary),
    hasMetroRoute:
      routeSummary?.mode === "metro",
  };

  return (
    <main className="mx-auto w-full max-w-3xl bg-[#f5f7f3] px-3 py-4 pb-24 sm:px-6 sm:py-5 sm:pb-8">
      <div className="flex w-full flex-col gap-4 sm:gap-5">

        <ScoreHeader
          totalPoints={totalPoints}
          visitedCount={visitedCount}
          onBack={onBack}
        />

        <ScoreProfileCard user={user} />

        <JourneyProgress
          visited={visitedCount}
          total={totalPandals}
          percentage={percentage}
          remaining={remaining}
        />

        <ScoreStats
          scorecardStats={scorecardStats}
          categoryCounts={categoryCounts}
          routeSummary={routeSummary}
        />

        <CrowdReporterCard
          pandals={pandals}
        />

        <RouteActivity
          routeSummary={routeSummary}
        />

        <Achievements
          achievementStats={achievementStats}
        />

        <VisitHistory
          visits={visits}
        />

      </div>
    </main>
  );
};

export default ScorecardPage;